# Notes:
#  1) Runners are executed in order. By default, they are blocking, except if concurrent = true.
#  2) end_all_on_exit = true, for concurrent runners, instructs the session to end if this specific process ends.
#  3) Eventually, [[runners.build]] will also be available. Separating the two makes it less convoluted and more flexible.

[[dev.runners]]
name = "npm_install"
cmd = "npm"
args = ["install"]

[[dev.runners]]
name = "tauri_icons"
when.no_file_at = "src-tauri/icons/32x32.png"
cmd = "npm"
args = ["run", "tauri", "icon", "src-tauri/icons/app-icon.png"]

[[dev.runners]]
name = "cargo_build"
working_dir = "src-tauri/"
cmd = "cargo"
args = ["build"]

[[dev.runners]]
name = "pcss"
cmd = "npm"
args = ["run", "pcss", "--", "-w"]
concurrent = true 
# if this process exit, end the dev session
end_all_on_exit = true

[[dev.runners]]
name = "rollup"
cmd = "npm"
args = ["run", "rollup", "--", "-w"]
concurrent = true
end_all_on_exit = true

[[dev.runners]]
name = "localhost"
cmd = "npm"
args = ["run", "localhost"]
concurrent = true
end_all_on_exit = true

[[dev.runners]]
name = "tauri_dev"
wait_before = 2000 # wait in ms, before getting called
cmd = "npm"
args = ["run", "tauri", "dev"]
concurrent = true
end_all_on_exit = true